markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-Flavored Markdown

# Site-wide variables available to all pages via the `site` variable, ex: `{{ site.github_url }}`
github_url: https://github.com/block/elasticgraph
discord_url: https://discord.gg/8m9FqJ7a7F
x_url: https://x.com/elasticgraph
x_username: "@ElasticGraph"
support_email: elasticgraph@squareup.com
tagline: Schema-driven, scalable, cloud-native, batteries-included GraphQL with superpowers.
description: ElasticGraph is an open-source framework for indexing, searching, and aggregating data powered by GraphQL and Elasticsearch / OpenSearch.

# Include `_index.html` file from docs directories
# https://github.com/lsegal/yard/issues/1027
include:
  - _index.html

# Reusable CSS styling for the site, available via the `site.style` variable, ex: `{{ site.style.body }}`
style:
  body: bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 flex flex-col h-screen
  link: text-blue-600 dark:text-blue-400 hover:underline
  navbar_dropdown: relative rounded-lg bg-white dark:bg-gray-700 shadow-lg border border-gray-200/80 dark:border-gray-600/50
  dropdown_pip: absolute -top-1.5 left-4 h-3 w-3 bg-white dark:bg-gray-700 transform rotate-45 border-t border-l border-gray-200/80 dark:border-gray-600/50

demo_oneliner: "curl -s https://raw.githubusercontent.com/block/elasticgraph/refs/heads/main/config/docker_demo/docker-compose.yaml | docker compose -f - up"
localhost_eg_url: "http://localhost:9000/"
